# AI Model API Keys
OPENAI_API_KEY: ""
ANTHROPIC_API_KEY: ""
ZHIPU_API_KEY: ""
DEEPSEEK_API_KEY: ""
KIMI_API_KEY: ""
ARK_API_KEY: ""
ARK_ENDPOINT: ""
QWEN_API_KEY: ""
QWEN_ENDPOINT: ""
YURI_API_KEY: ""
YURI_ENDPOINT: ""
MINIMAX_API_KEY: ""
GEMINI_API_KEY: ""

# App Settings
HOST: "0.0.0.0"
PORT: 5000
DEBUG: false
